[theme]
base = "light"
primaryColor = "#2a78d6"
backgroundColor = "#fcfcfb"
secondaryBackgroundColor = "#f1f0ec"
textColor = "#0b0b0b"
font = "sans serif"

[server]
# headless = false -> Streamlit opens your default browser automatically
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
